### ISSUE TITLE
ValidateURL error

### ISSUE THREAD

**Issue by aikozijlemans** [hydrox19/discord-music#10]
Hello I am getting the following error
/*****************************************************************************************************
 * validateURL will be renamed to validateID to match with getPlaylistID in the next release of ytpl *
 *                   set `ytpl.do_warn_deprecate = false` to disable this message                    *
 *****************************************************************************************************/

**Comment by inhydrox** [comment]
Ignore it it's not really an issue.

**Comment by jeremyzijlemans** [comment]
But it doesn't play at all?

**Comment by inhydrox** [comment]
Yeah because some package current version of discord-player uses got takedown

**Comment by inhydrox** [comment]
I will rewrite this whole repository and remove discord-player completely

**Comment by jeremyzijlemans** [comment]
ah okay

**Comment by Nailed-it1** [comment]
i have this to. is there anyway of fixing it for now until you update it?
